
project_id = "wonderwhiz-production"

[functions.generate-curiosity-blocks]
verify_jwt = true

[functions.generate-quick-answer]
verify_jwt = true

[functions.groq-wonder-suggestions]
verify_jwt = true

[functions.increment-sparks-balance]
verify_jwt = true
