
[functions]

[functions.generate-gemini-image]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-curio-suggestions]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false
