
project_id = "turexhnvsvmllwitllmg"

[functions.analyze-image]
verify_jwt = false

[functions.generate-contextual-image]
verify_jwt = false

[functions.generate-curiosity-blocks]
verify_jwt = false

[functions.handle-block-chat]
verify_jwt = false

[functions.increment-sparks-balance]
verify_jwt = false
