
project_id = "turexhnvsvmllwitllmg"

[functions.gemini-live-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-gemini-image]
verify_jwt = false

[functions.save-content-block]
verify_jwt = false

[functions.generate-contextual-image]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.generate-curio-suggestions]
verify_jwt = false

[functions.handle-block-replies]
verify_jwt = false

[functions.handle-interaction]
verify_jwt = false
