
project_id = "turexhnvsvmllwitllmg"
allowed_http_methods = ["POST", "OPTIONS"]
[global.headers]
Content-Type = "application/json"
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"
