// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-children.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-children.ts
var list_children_default = defineTool({
  name: "list_child_profiles",
  title: "List child profiles",
  description: "List the signed-in parent's child learner profiles on WonderWhiz.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("child_profiles").select("id, name, age, interests, language, sparks_balance, streak_days, last_active_date").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profiles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-topics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var list_topics_default = defineTool2({
  name: "list_learning_topics",
  title: "List learning topics",
  description: "List learning topics for one of the parent's children. Returns most recent first.",
  inputSchema: {
    child_id: z.string().uuid().describe("Child profile id (from list_child_profiles)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ child_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("learning_topics").select("id, title, description, status, current_section, total_sections, child_age, created_at, updated_at").eq("child_id", child_id).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { topics: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-topic.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_topic_default = defineTool3({
  name: "get_learning_topic",
  title: "Get learning topic with sections",
  description: "Fetch a single learning topic and its sections (title, content, facts) for one of the parent's children.",
  inputSchema: {
    topic_id: z2.string().uuid().describe("Learning topic id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ topic_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser(ctx);
    const { data: topic, error: tErr } = await client.from("learning_topics").select("id, title, description, status, current_section, total_sections, child_id, child_age, table_of_contents, created_at, updated_at").eq("id", topic_id).maybeSingle();
    if (tErr) return { content: [{ type: "text", text: tErr.message }], isError: true };
    if (!topic) return { content: [{ type: "text", text: "Topic not found" }], isError: true };
    const { data: sections, error: sErr } = await client.from("learning_sections").select("id, section_number, title, content, facts, word_count, image_url").eq("topic_id", topic_id).order("section_number", { ascending: true });
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    const result = { topic, sections: sections ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lzoysqczxxsqkvfsqygp";
var mcp_default = defineMcp({
  name: "wonderwhiz-mcp",
  title: "WonderWhiz",
  version: "0.1.0",
  instructions: "Read WonderWhiz learning data for the signed-in parent. Use list_child_profiles first, then list_learning_topics for a child, then get_learning_topic for full section content.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_children_default, list_topics_default, get_topic_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
