// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://turexhnvsvmllwitllmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1cmV4aG52c3ZtbGx3aXRsbG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTg3NzEsImV4cCI6MjA1Nzg3NDc3MX0.8OYLQq3yhSDD_RsWeHIuFVgLJUEeu6NDQ2aYpTtcfCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false
  }
});